### ISSUE TITLE
AttributeError: 'module' object has no attribute 'cv'

### ISSUE THREAD

**Issue by darcihp** [bqlabs/horus#119]
Hello,

I'm using Ubuntu 14.04 and a C230 logitech camera to my scanner.

I am just following the steps presented here: [http://horus.readthedocs.io/en/release-0.2/source/installation/ubuntu.html](url) but when a try to connect the message appear:

> 
>>> Horus 0.1.2.4 <<<
>>> Connecting camera 0
>>> Done
Corrupt JPEG data: 2 extraneous bytes before marker 0xd0
Corrupt JPEG data: 2 extraneous bytes before marker 0xd4
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/dist-packages/horus/src/horus/engine/driver.py", line 70, in _connect
    self.camera.connect()
  File "/usr/lib/python2.7/dist-packages/horus/src/horus/engine/camera.py", line 124, in connect
    self.checkCamera()
  File "/usr/lib/python2.7/dist-packages/horus/src/horus/engine/camera.py", line 149, in checkCamera
    self.setExposure(2)
  File "/usr/lib/python2.7/dist-packages/horus/src/horus/engine/camera.py", line 250, in setExposure
    self.capture.set(cv2.cv.CV_CAP_PROP_EXPOSURE, value)
AttributeError: 'module' object has no attribute 'cv'

Can someone help me to solve this problem?

**Comment by gecedwards** [comment]
Did you try with version 2? ( https://github.com/bqlabs/horus ) dont install it, clone it and try to run it from the horus folder.
