### ISSUE TITLE
Traceback on wxPython 3 with GTK 3

### ISSUE THREAD

**Issue by hroncok** [bqlabs/horus#57]
When I use wxPython 3 with GTK 3, I get the following traceback when exiting Horus:

```python
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/horus/gui/welcome.py", line 71, in onClose
    self.EndModal(wx.ID_OK)
  File "/usr/lib64/python2.7/site-packages/wx-3.0-gtk3/wx/_windows.py", line 809, in EndModal
    return _windows_.Dialog_EndModal(*args, **kwargs)
wx._core.PyAssertionError: C++ assertion "Assert failure" failed at ./src/gtk/dialog.cpp(201) in EndModal(): either wxDialog:EndModal called twice or ShowModal wasn't called
```

**Comment by Jesus89** [comment]
Hi, can you test this with 0.2b1 version?
