### ISSUE TITLE
Get an error when trying to upload firmware in arduino Uno

### ISSUE THREAD

**Issue by deusyss** [bqlabs/horus#67]
Configuration:
-Linux Mint 17.3
-Follow installation instruction for Debian Like OS
-clone git repository and launch directly ./horus from this clone

When i open the Edit Menu/preference, and ask to upload the firmware in my arduino Uno, get the following message in my terminal:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/Horus-0.2b1-py2.7.egg/horus/gui/util/preferences.py", line 185, in on_upload_firmware
    self.before_load_firmware()
  File "/usr/local/lib/python2.7/dist-packages/Horus-0.2b1-py2.7.egg/horus/gui/util/preferences.py", line 227, in before_load_firmware
    self.get_sizer().Layout()
AttributeError: 'PreferencesDialog' object has no attribute 'get_sizer'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/Horus-0.2b1-py2.7.egg/horus/gui/util/preferences.py", line 185, in on_upload_firmware
    self.before_load_firmware()
  File "/usr/local/lib/python2.7/dist-packages/Horus-0.2b1-py2.7.egg/horus/gui/util/preferences.py", line 227, in before_load_firmware
    self.get_sizer().Layout()
AttributeError: 'PreferencesDialog' object has no attribute 'get_sizer'

**Comment by Jesus89** [comment]
Hi,

This is fixed on release/0.2 branch. Now I have merged this branch into develop.

Thanks.
