### ISSUE TITLE
Scan freeze issue

### ISSUE THREAD

**Issue by vincpad** [bqlabs/horus#82]
Hello,
I'm using Horus 0.2rc1 on windows with a bq ciclop for something like 2 weeks, and today i'm starting having freeze issues during scans.
It happens quite frequently, on a least 3 out of 4 scans (using the same settings for each scan).
Here is what is printed in the console (with one scan completed and another that freezed)
```
2016-06-08 17:06:32.621 - Start application Horus 0.2rc1
2016-06-08 17:06:38.342 - Connecting camera 0
2016-06-08 17:06:39.375 -  Done
2016-06-08 17:06:39.377 - Connecting board COM3 115200
2016-06-08 17:06:41.119 -  Done
2016-06-08 17:06:43.203 - Start scan
2016-06-08 17:12:57.650 - Finish scan 100 %  Time 06' 14"
2016-06-08 17:16:46.907 - Start scan
Exception in thread Thread-47:
Traceback (most recent call last):
  File "C:\Program Files (x86)\Horus2\python\lib\threading.py", line 552, in __bootstrap_inner
    self.run()
  File "C:\Program Files (x86)\Horus2\python\lib\threading.py", line 505, in run
    self.__target(*self.__args, **self.__kwargs)
  File "src\horus\engine\scan\ciclop_scan.py", line 222, in _process
    self._process_capture(capture)
  File "src\horus\engine\scan\ciclop_scan.py", line 279, in _process_capture
    texture = capture.texture[v, np.around(u).astype(int)].T
IndexError: index 973 is out of bounds for axis 1 with size 960
```
After this freeze the software isn't crashed itself, I can stop the scan and make things.

**Comment by Jesus89** [comment]
Thanks for the report!

Can you send me your calibration profile? This would be helpful.

**Comment by vincpad** [comment]
Sure, here is also another crash report
```
Exception in thread Thread-9:
Traceback (most recent call last):
  File "C:\Program Files (x86)\Horus2\python\lib\threading.py", line 552, in __bootstrap_inner
    self.run()
  File "C:\Program Files (x86)\Horus2\python\lib\threading.py", line 505, in run
    self.__target(*self.__args, **self.__kwargs)
  File "src\horus\engine\scan\ciclop_scan.py", line 222, in _process
    self._process_capture(capture)
  File "src\horus\engine\scan\ciclop_scan.py", line 279, in _process_capture


    texture = capture.texture[v, np.around(u).astype(int)].T
IndexError: index 1197 is out of bounds for axis 1 with size 960
```
(Github doesn't want me to upload my archive, so I've put them on on pastebin)
[http://pastebin.com/YJwDVNgJ](http://pastebin.com/YJwDVNgJ)
[http://pastebin.com/ynNz3Pmr](http://pastebin.com/ynNz3Pmr)

**Comment by Jesus89** [comment]
Hi, It has an easy solution that will be available in 0.2rc2. But I need to understand what's going on.

Can you get this error with all scanned objects, or only with some particular ones?

**Comment by Jesus89** [comment]
Hi, I have a clue. You are using RANSAC method for scanning. This method only will be available for laser segmentation in calibration.

**Solution**: select None or SGF in the section: ![Scan segmentation](http://horus.readthedocs.io/en/release-0.2/source/workbenches/adjustment.html#segmentation).

Btw, here you have the difference between the two methods: ![SGF](http://nbviewer.jupyter.org/github/Jesus89/3DScanScience/blob/master/notebooks/3.1.%20Laser%20segmentation.ipynb#Segmented-gaussian-filter) ![RANSAC](http://nbviewer.jupyter.org/github/Jesus89/3DScanScience/blob/master/notebooks/3.2.%20Laser%20segmentation%20in%20pattern.ipynb#RANSAC)

**Comment by vincpad** [comment]
Oh, yes, I chose this method because I understood that it was more efficient (but I didn't look further).
Thank you !
